# Generated by Django 6.0.4 on 2026-07-01 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='رمز التحقق المشفر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق البريد',
                'verbose_name_plural': 'رموز تحقق البريد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'created_at'], name='account_ema_user_id_516fc9_idx')],
            },
        ),
    ]
