# Generated by Django 6.0.4 on 2026-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من البريد الإلكتروني'),
        ),
    ]
