# Generated by Django 6.0.4 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('account_created', 'إنشاء حساب'),
                    ('project_started', 'بدء مشروع'),
                    ('project_submitted', 'استلام مشروع'),
                    ('project_graded', 'تقييم مشروع'),
                    ('password_reset', 'إعادة تعيين كلمة المرور'),
                ],
                default='project_graded',
                max_length=30,
                verbose_name='نوع الإشعار',
            ),
        ),
    ]
