# Generated by Django 6.0.4 on 2026-07-01

from django.db import migrations


def mark_existing_users_verified(apps, schema_editor):
    CustomUser = apps.get_model('account', 'CustomUser')
    CustomUser.objects.filter(is_active=True, email_verified=False).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_notification_project_started'),
    ]

    operations = [
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
