# Generated by Django 6.0.4 on 2026-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_backfill_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, null=True, verbose_name='مستوى المستخدم'),
        ),
    ]
