# Generated by Django 6.0.4 on 2026-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_tasksubmission_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('react', 'React'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('rust', 'Rust'), ('other', 'أخرى')], help_text='لغة البرمجة الرئيسية للمشروع', max_length=20, verbose_name='لغة البرمجة'),
        ),
    ]
