# Generated by Django 6.0.4 on 2026-07-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_tests_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='قائمة لغات البرمجة المستخدمة في المشروع', verbose_name='لغات المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('json', 'JSON'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('svelte', 'Svelte'), ('nextjs', 'Next.js'), ('nuxt', 'Nuxt.js'), ('sass', 'Sass'), ('scss', 'SCSS'), ('less', 'Less'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('jquery', 'jQuery'), ('python', 'Python'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('rust', 'Rust'), ('other', 'أخرى')], help_text='اللغة الأولى ضمن قائمة لغات المشروع (للتوافق مع الإصدارات السابقة)', max_length=20, verbose_name='لغة البرمجة الرئيسية'),
        ),
    ]
