# Generated by Django 6.0 on 2026-07-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_backfill_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة تعبيرية للمشروع', null=True, upload_to='project_images/', verbose_name='صورة المشروع'),
        ),
    ]
