# Generated by Django 6.0 on 2026-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='الصورة التي ستظهر في بطاقة المشروع', null=True, upload_to='project_images/', verbose_name='صورة المشروع'),
        ),
    ]
