# Generated by Django 6.0 on 2026-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة اختيارية تعبر عن المشروع', null=True, upload_to='projects/', verbose_name='صورة المشروع'),
        ),
    ]
