# Generated by Django 6.0.4 on 2026-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة تعبيرية للمشروع تظهر في البطاقات', null=True, upload_to='project_images/', verbose_name='صورة المشروع'),
        ),
    ]
