# Generated by Django 6.0 on 2026-07-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_workspacebranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='projects.projecttask'),
        ),
    ]
