from placement.constants import DIFFICULTY_SCORES

PYTHON_PLACEMENT_QUESTIONS = [
    # Basics - Beginner
    {
        'question': 'أي نوع بيانات يُستخدم لتخزين النص في Python؟',
        'options': ['int', 'str', 'bool', 'list'],
        'correct_answer': 1,
        'explanation': 'str يُستخدم لتخزين النصوص في Python.',
        'topic': 'basics',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'ما ناتج التعبير 10 // 3 في Python؟',
        'options': ['3.33', '3', '4', '1'],
        'correct_answer': 1,
        'explanation': '// هو قسمة صحيحة وتُرجع 3.',
        'topic': 'basics',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي دالة تُستخدم لطباعة قيمة في Python؟',
        'options': ['echo()', 'print()', 'console()', 'output()'],
        'correct_answer': 1,
        'explanation': 'print() هي الدالة الأساسية للطباعة.',
        'topic': 'basics',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي رمز يُستخدم للتعليق على سطر واحد؟',
        'options': ['//', '#', '--', '/*'],
        'correct_answer': 1,
        'explanation': 'Python يستخدم # للتعليقات.',
        'topic': 'basics',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # Basics - Intermediate
    {
        'question': 'ما ناتج bool("") في Python؟',
        'options': ['True', 'False', 'None', 'Error'],
        'correct_answer': 1,
        'explanation': 'السلسلة الفارغة تُقيّم إلى False.',
        'topic': 'basics',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي تعبير يحوّل النص "42" إلى عدد صحيح؟',
        'options': ['str(42)', 'int("42")', 'float("42")', 'bool("42")'],
        'correct_answer': 1,
        'explanation': 'int("42") يُرجع العدد 42.',
        'topic': 'basics',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما ناتج "Py" + "thon"؟',
        'options': ['Python', 'Py thon', 'Error', 'Py+thon'],
        'correct_answer': 0,
        'explanation': '+ يدمج السلاسل النصية.',
        'topic': 'basics',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي نوع يُرجعه التعبير 3 / 2 في Python 3؟',
        'options': ['int', 'float', 'str', 'bool'],
        'correct_answer': 1,
        'explanation': 'القسمة العادية / تُرجع float في Python 3.',
        'topic': 'basics',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # Basics - Advanced
    {
        'question': 'ما ناتج list(range(2, 8, 2))؟',
        'options': ['[2, 4, 6]', '[2, 3, 4, 5, 6, 7]', '[2, 8]', '[0, 2, 4, 6]'],
        'correct_answer': 0,
        'explanation': 'range(2, 8, 2) يولّد 2, 4, 6.',
        'topic': 'basics',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي بنية تُنفّذ كتلة عند تحقق شرط؟',
        'options': ['for', 'while', 'if', 'try'],
        'correct_answer': 2,
        'explanation': 'if تُستخدم للتفرع الشرطي.',
        'topic': 'basics',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما ناتج len("Python")؟',
        'options': ['5', '6', '7', 'Error'],
        'correct_answer': 1,
        'explanation': 'Python فيها 6 أحرف.',
        'topic': 'basics',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي كلمة محجوزة تُستخدم لتعريف دالة؟',
        'options': ['func', 'def', 'function', 'lambda only'],
        'correct_answer': 1,
        'explanation': 'def تبدأ تعريف الدالة.',
        'topic': 'basics',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # Basics - Expert
    {
        'question': 'ما ناتج [x * 2 for x in range(3)]؟',
        'options': ['[0, 2, 4]', '[2, 4, 6]', '[0, 1, 2]', '[1, 2, 3]'],
        'correct_answer': 0,
        'explanation': 'range(3) = 0,1,2 ثم ضرب كل عنصر في 2.',
        'topic': 'basics',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي تعبير يتحقق من وجود مفتاح في dict؟',
        'options': ['key in d', 'd.has(key)', 'd.contains(key)', 'exists(d, key)'],
        'correct_answer': 0,
        'explanation': 'in تفحص وجود المفتاح في القاموس.',
        'topic': 'basics',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما ناتج isinstance(3.0, int)؟',
        'options': ['True', 'False', 'None', 'Error'],
        'correct_answer': 1,
        'explanation': '3.0 من نوع float وليس int.',
        'topic': 'basics',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي دالة تُرجع أكبر عنصر في iterable؟',
        'options': ['top()', 'max()', 'high()', 'largest()'],
        'correct_answer': 1,
        'explanation': 'max() تُرجع أكبر عنصر.',
        'topic': 'basics',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    # Data structures - Beginner
    {
        'question': 'أي بنية تُستخدم لتخزين مجموعة مرتبة قابلة للتعديل؟',
        'options': ['tuple', 'list', 'set', 'dict'],
        'correct_answer': 1,
        'explanation': 'list مرتبة وقابلة للتعديل.',
        'topic': 'data_structures',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'ما ناتج [1, 2, 3][1]؟',
        'options': ['1', '2', '3', 'Error'],
        'correct_answer': 1,
        'explanation': 'الفهرس 1 يُشير للعنصر الثاني.',
        'topic': 'data_structures',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي دالة تُضيف عنصراً في نهاية list؟',
        'options': ['add()', 'append()', 'push()', 'insert_end()'],
        'correct_answer': 1,
        'explanation': 'append() تُضيف في النهاية.',
        'topic': 'data_structures',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي بنية تخزّن أزواج مفتاح-قيمة؟',
        'options': ['list', 'tuple', 'dict', 'set'],
        'correct_answer': 2,
        'explanation': 'dict تخزّن مفاتيح وقيم.',
        'topic': 'data_structures',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # Data structures - Intermediate
    {
        'question': 'ما ناتج {"a": 1}.get("b", 0)؟',
        'options': ['None', '0', 'Error', '1'],
        'correct_answer': 1,
        'explanation': 'get تُرجع القيمة الافتراضية عند غياب المفتاح.',
        'topic': 'data_structures',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي بنية لا تسمح بالتكرار؟',
        'options': ['list', 'tuple', 'set', 'dict keys only sometimes'],
        'correct_answer': 2,
        'explanation': 'set لا تحتوي عناصر مكررة.',
        'topic': 'data_structures',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما ناتج len({"x": 1, "y": 2})؟',
        'options': ['1', '2', '3', 'Error'],
        'correct_answer': 1,
        'explanation': 'len(dict) يُرجع عدد المفاتيح.',
        'topic': 'data_structures',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي طريقة تُحوّل list إلى tuple؟',
        'options': ['list()', 'tuple()', 'set()', 'dict()'],
        'correct_answer': 1,
        'explanation': 'tuple(my_list) تُنشئ tuple.',
        'topic': 'data_structures',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # Data structures - Advanced
    {
        'question': 'ما ناتج sorted([3, 1, 2])؟',
        'options': ['[3, 1, 2]', '[1, 2, 3]', '[2, 1, 3]', 'Error'],
        'correct_answer': 1,
        'explanation': 'sorted تُرجع نسخة مرتبة.',
        'topic': 'data_structures',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي تعبير ينسخ list بشكل سطحي؟',
        'options': ['a = b', 'a = b.copy()', 'a = b[0]', 'a = list(b[0])'],
        'correct_answer': 1,
        'explanation': 'copy() تُنشئ نسخة سطحية.',
        'topic': 'data_structures',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما ناتج [1, 2] + [3]؟',
        'options': ['[4]', '[1, 2, 3]', '[3, 1, 2]', 'Error'],
        'correct_answer': 1,
        'explanation': '+ يدمج قائمتين.',
        'topic': 'data_structures',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي دالة تُزيل عنصراً حسب القيمة مرة واحدة من list؟',
        'options': ['delete()', 'remove()', 'pop()', 'discard()'],
        'correct_answer': 1,
        'explanation': 'remove(value) تزيل أول تطابق.',
        'topic': 'data_structures',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # Data structures - Expert
    {
        'question': 'ما ناتج {x for x in "aab"}؟',
        'options': ['{"a", "b"}', '["a", "b"]', '{"a": "b"}', 'Error'],
        'correct_answer': 0,
        'explanation': 'set comprehension تُنشئ مجموعة فريدة.',
        'topic': 'data_structures',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي بنية مناسبة كمفتاح dict؟',
        'options': ['list', 'dict', 'tuple', 'set'],
        'correct_answer': 2,
        'explanation': 'tuple قابلة للتجزئة ويمكن استخدامها كمفتاح.',
        'topic': 'data_structures',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما ناتج list(reversed([1, 2, 3]))؟',
        'options': ['[3, 2, 1]', 'reversed object converted to list', '[1, 2, 3]', 'Error'],
        'correct_answer': 1,
        'explanation': 'list(reversed(...)) تُحوّل المعكوس إلى قائمة [3,2,1].',
        'topic': 'data_structures',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي تعبير يدمج قائمتين في dict من مفاتيح وقيم؟',
        'options': ['dict(a, b)', 'dict(zip(keys, values))', 'dict.merge()', '{keys: values}'],
        'correct_answer': 1,
        'explanation': 'zip + dict طريقة شائعة للدمج.',
        'topic': 'data_structures',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    # OOP - Beginner
    {
        'question': 'أي كلمة تُستخدم لتعريف class في Python؟',
        'options': ['struct', 'class', 'object', 'type only'],
        'correct_answer': 1,
        'explanation': 'class تُعرّف الصنف.',
        'topic': 'oop',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'ما اسم الدالة الخاصة التي تُستدعى عند إنشاء كائن؟',
        'options': ['__init__', '__new__ only', '__start__', '__create__'],
        'correct_answer': 0,
        'explanation': '__init__ هي المُنشئ الشائع.',
        'topic': 'oop',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي متغير يُمثل المرجع للكائن الحالي داخل method؟',
        'options': ['this', 'self', 'me', 'current'],
        'correct_answer': 1,
        'explanation': 'self هو الاسم المتعارف عليه.',
        'topic': 'oop',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي بنية تُستخدم لمعالجة الأخطاء؟',
        'options': ['if/else', 'try/except', 'for/while', 'with/import'],
        'correct_answer': 1,
        'explanation': 'try/except لمعالجة الاستثناءات.',
        'topic': 'oop',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # OOP - Intermediate
    {
        'question': 'ما الذي يحدث عند raise ValueError("msg")؟',
        'options': ['يطبع رسالة', 'يرمي استثناء', 'ينهي البرنامج دائماً', 'لا شيء'],
        'correct_answer': 1,
        'explanation': 'raise يرمي استثناء.',
        'topic': 'oop',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي كلمة تُستخدم لاستدعاء method من parent class؟',
        'options': ['parent()', 'super()', 'base()', 'extend()'],
        'correct_answer': 1,
        'explanation': 'super() يستدعي الأب.',
        'topic': 'oop',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي block يُنفّذ دائماً بعد try/except حتى مع raise؟',
        'options': ['else', 'finally', 'always', 'ensure'],
        'correct_answer': 1,
        'explanation': 'finally يُنفّذ في النهاية.',
        'topic': 'oop',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما الفرق الأساسي بين class attribute و instance attribute؟',
        'options': [
            'لا فرق',
            'class attribute مشترك بين كل الكائنات',
            'instance attribute ثابت',
            'class attribute لا يمكن قراءته',
        ],
        'correct_answer': 1,
        'explanation': 'صفة الصنف مشتركة بين كل النسخ.',
        'topic': 'oop',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # OOP - Advanced
    {
        'question': 'أي decorator شائع لتحويل method إلى property؟',
        'options': ['@static', '@property', '@classmethod only', '@cached'],
        'correct_answer': 1,
        'explanation': '@property يجعل method كصفة.',
        'topic': 'oop',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي method لا يستقبل self ولا cls؟',
        'options': ['instance method', 'classmethod', 'staticmethod', '__init__'],
        'correct_answer': 2,
        'explanation': 'staticmethod لا يحتاج self أو cls.',
        'topic': 'oop',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما نتيجة except Exception as e؟',
        'options': ['تمنع كل الأخطاء', 'تلتقط الاستثناء في e', 'تُعيد raise', 'تُغلق البرنامج'],
        'correct_answer': 1,
        'explanation': 'as e يحفظ الاستثناء في متغير.',
        'topic': 'oop',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي مفهوم يسمح لصنف بوراثة سلوك صنف آخر؟',
        'options': ['composition only', 'inheritance', 'import', 'lambda'],
        'correct_answer': 1,
        'explanation': 'inheritance يرث الصفات والmethods.',
        'topic': 'oop',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # OOP - Expert
    {
        'question': 'أي دالة تُستخدم لفتح ملف بأمان مع إغلاق تلقائي؟',
        'options': ['open() only', 'with open(...) as f', 'file()', 'read()'],
        'correct_answer': 1,
        'explanation': 'with statement يضمن الإغلاق.',
        'topic': 'oop',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما الذي يفعله __str__ عادةً؟',
        'options': ['يحذف الكائن', 'يُرجع تمثيلاً نصياً للكائن', 'ينسخ الكائن', 'يُنشئ class'],
        'correct_answer': 1,
        'explanation': '__str__ للتمثيل النصي.',
        'topic': 'oop',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي استثناء يُرمى عند فهرسة list خارج النطاق؟',
        'options': ['KeyError', 'IndexError', 'ValueError', 'TypeError'],
        'correct_answer': 1,
        'explanation': 'IndexError للفهرسة غير الصالحة.',
        'topic': 'oop',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي مفهوم يُطبّق "فتح/إغلاق" الموارد تلقائياً؟',
        'options': ['iterator protocol', 'context manager', 'generator only', 'decorator only'],
        'correct_answer': 1,
        'explanation': 'context manager يعمل مع with.',
        'topic': 'oop',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
]
