from placement.constants import DIFFICULTY_SCORES

PLACEMENT_QUESTIONS = [
    # HTML - Beginner
    {
        'question': 'أي وسم يُستخدم لإنشاء أكبر عنوان في الصفحة؟',
        'options': ['<p>', '<h1>', '<title>', '<header>'],
        'correct_answer': 1,
        'explanation': 'الوسم <h1> يمثل العنوان الرئيسي في HTML.',
        'topic': 'html',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي وسم يُستخدم لإدراج رابط تشعبي؟',
        'options': ['<link>', '<a>', '<href>', '<url>'],
        'correct_answer': 1,
        'explanation': 'الوسم <a> يُستخدم لإنشاء الروابط مع خاصية href.',
        'topic': 'html',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أين يوضع محتوى الصفحة المرئي عادةً؟',
        'options': ['<head>', '<body>', '<meta>', '<style>'],
        'correct_answer': 1,
        'explanation': 'كل المحتوى الظاهر للمستخدم يوضع داخل <body>.',
        'topic': 'html',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي وسم ينشئ قائمة غير مرتبة؟',
        'options': ['<ol>', '<ul>', '<li>', '<list>'],
        'correct_answer': 1,
        'explanation': '<ul> لقائمة نقطية و<ol> لقائمة مرقمة.',
        'topic': 'html',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # HTML - Intermediate
    {
        'question': 'ما الغرض من <!DOCTYPE html>؟',
        'options': [
            'تنسيق الصفحة',
            'تحديد نوع المستند HTML5',
            'إضافة JavaScript',
            'إنشاء جدول',
        ],
        'correct_answer': 1,
        'explanation': 'DOCTYPE يخبر المتصفح أن المستند من نوع HTML5.',
        'topic': 'html',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي خاصية تجعل حقل الإدخال إلزامياً؟',
        'options': ['disabled', 'required', 'readonly', 'checked'],
        'correct_answer': 1,
        'explanation': 'required تمنع إرسال النموذج بدون تعبئة الحقل.',
        'topic': 'html',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما الفرق بين <div> و<span>؟',
        'options': [
            '<div> عنصر سطري و<span> كتلي',
            '<div> عنصر كتلي و<span> عنصر سطري',
            'لا يوجد فرق',
            'كلاهما للروابط فقط',
        ],
        'correct_answer': 1,
        'explanation': '<div> كتلي block و<span> سطري inline.',
        'topic': 'html',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي وسم يُستخدم لعرض صورة؟',
        'options': ['<picture>', '<img>', '<image>', '<src>'],
        'correct_answer': 1,
        'explanation': '<img> مع src وalt هو الوسم القياسي للصور.',
        'topic': 'html',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # HTML - Advanced
    {
        'question': 'ما فائدة خاصية alt في <img>؟',
        'options': [
            'تغيير حجم الصورة',
            'نص بديل لإمكانية الوصول',
            'ربط CSS',
            'تشغيل الصورة كفيديو',
        ],
        'correct_answer': 1,
        'explanation': 'alt يوفّر وصفاً للصورة عند تعذر عرضها أو لقارئات الشاشة.',
        'topic': 'html',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي عنصر يمثل تذييل الصفحة دلالياً؟',
        'options': ['<bottom>', '<section>', '<footer>', '<aside>'],
        'correct_answer': 2,
        'explanation': '<footer> عنصر دلالي لتذييل الصفحة أو القسم.',
        'topic': 'html',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما نوع input المناسب لإدخال بريد إلكتروني؟',
        'options': ['text', 'email', 'url', 'search'],
        'correct_answer': 1,
        'explanation': 'type="email" يوفّر تحققاً أولياً من صيغة البريد.',
        'topic': 'html',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي وسم يربط ملف CSS خارجي؟',
        'options': [
            '<style src="...">',
            '<link rel="stylesheet" href="...">',
            '<css href="...">',
            '<script src="style.css">',
        ],
        'correct_answer': 1,
        'explanation': 'link مع rel="stylesheet" يربط ملف CSS خارجي.',
        'topic': 'html',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # HTML - Expert
    {
        'question': 'ما دور خاصية defer في <script src="...">؟',
        'options': [
            'تشغيل السكربت قبل تحليل HTML',
            'تأجيل التنفيذ حتى اكتمال تحليل HTML',
            'منع التخزين المؤقت',
            'تحويل السكربت إلى CSS',
        ],
        'correct_answer': 1,
        'explanation': 'defer يؤجل تنفيذ السكربت الخارجي دون حجب التحليل.',
        'topic': 'html',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي عنصر دلالي يمثل محتوى مستقل؟',
        'options': ['<article>', '<span>', '<b>', '<i>'],
        'correct_answer': 0,
        'explanation': '<article> يمثل محتوى مستقل مثل تدوينة أو بطاقة خبر.',
        'topic': 'html',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما الفرق بين <button type="submit"> و type="button"؟',
        'options': [
            'لا فرق',
            'submit يرسل النموذج وbutton لا',
            'button يرسل النموذج وsubmit لا',
            'كلاهما يعطل النموذج',
        ],
        'correct_answer': 1,
        'explanation': 'type="submit" يرسل النموذج بينما button لا يرسله افتراضياً.',
        'topic': 'html',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي خاصية تربط label بحقل input؟',
        'options': ['name', 'for', 'id', 'value'],
        'correct_answer': 1,
        'explanation': 'for في label يجب أن يطابق id الحقل المرتبط.',
        'topic': 'html',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    # CSS - Beginner
    {
        'question': 'أي خاصية تغيّر لون النص؟',
        'options': ['background-color', 'color', 'font-style', 'border-color'],
        'correct_answer': 1,
        'explanation': 'color تتحكم بلون النص.',
        'topic': 'css',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'كيف نجعل النص عريضاً؟',
        'options': ['font-weight: bold', 'text-bold: true', 'style: bold', 'weight: heavy'],
        'correct_answer': 0,
        'explanation': 'font-weight: bold أو 700 يجعل النص عريضاً.',
        'topic': 'css',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي محدد يختار العنصر بمعرّف id="main"؟',
        'options': ['.main', '#main', 'main', '*main'],
        'correct_answer': 1,
        'explanation': '# يُستخدم لاختيار العناصر حسب id.',
        'topic': 'css',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي خاصية تتحكم بحجم الخط؟',
        'options': ['text-size', 'font-size', 'size', 'letter-size'],
        'correct_answer': 1,
        'explanation': 'font-size تحدد حجم الخط.',
        'topic': 'css',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # CSS - Intermediate
    {
        'question': 'ما نتيجة display: flex على العنصر الأب؟',
        'options': [
            'يخفي العناصر',
            'يجعل الأبناء في تخطيط مرن',
            'يحوّل النص إلى جدول',
            'يلغي الهوامش',
        ],
        'correct_answer': 1,
        'explanation': 'Flexbox ينظم العناصر الأبناء في صف أو عمود مرن.',
        'topic': 'css',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي خاصية تزيل الخط السفلي من الروابط؟',
        'options': ['text-decoration: none', 'underline: false', 'link-style: none', 'border: 0'],
        'correct_answer': 0,
        'explanation': 'text-decoration: none تزيل التسطير من الروابط.',
        'topic': 'css',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما وظيفة :hover؟',
        'options': [
            'تطبيق الأنماط عند الضغط فقط',
            'تطبيق الأنماط عند مرور المؤشر',
            'إخفاء العنصر',
            'تغيير الخط تلقائياً',
        ],
        'correct_answer': 1,
        'explanation': ':hover pseudo-class يطبّق الأنماط عند تمرير المؤشر.',
        'topic': 'css',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي وحدة نسبية تعتمد على حجم خط العنصر نفسه؟',
        'options': ['px', 'em', 'vh', 'cm'],
        'correct_answer': 1,
        'explanation': 'em تعتمد على font-size للعنصر الحالي.',
        'topic': 'css',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # CSS - Advanced
    {
        'question': 'ما الفرق بين margin و padding؟',
        'options': [
            'margin داخلي و padding خارجي',
            'margin خارجي و padding داخلي',
            'لا فرق',
            'padding للحدود فقط',
        ],
        'correct_answer': 1,
        'explanation': 'margin خارج الحدود وpadding داخلها حول المحتوى.',
        'topic': 'css',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي خاصية تنشئ شبكة CSS Grid؟',
        'options': ['display: grid', 'layout: grid', 'grid: true', 'flex: grid'],
        'correct_answer': 0,
        'explanation': 'display: grid يفعّل تخطيط الشبكة.',
        'topic': 'css',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما تأثير box-sizing: border-box؟',
        'options': [
            'العرض والارتفاع يشملان padding وborder',
            'يلغي الهوامش',
            'يخفي الحدود',
            'يحوّل العنصر إلى inline',
        ],
        'correct_answer': 0,
        'explanation': 'border-box يجعل width/height يشملان padding وborder.',
        'topic': 'css',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي خاصية تثبت عنصراً أثناء التمرير؟',
        'options': ['position: fixed', 'display: sticky-only', 'float: fixed', 'anchor: fixed'],
        'correct_answer': 0,
        'explanation': 'position: fixed يثبت العنصر بالنسبة لنافذة المتصفح.',
        'topic': 'css',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # CSS - Expert
    {
        'question': 'ما وظيفة justify-content في Flexbox؟',
        'options': [
            'محاذاة العناصر على المحور الرئيسي',
            'تغيير اتجاه النص فقط',
            'تحديد عدد الأعمدة',
            'إخفاء العناصر الزائدة',
        ],
        'correct_answer': 0,
        'explanation': 'justify-content يوزّع العناصر على المحور الرئيسي.',
        'topic': 'css',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي محدد له أعلى أولوية؟',
        'options': ['element', '.class', '#id', '*'],
        'correct_answer': 2,
        'explanation': 'محدد id أعلى أولوية من class والعنصر.',
        'topic': 'css',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما نتيجة grid-template-columns: repeat(3, 1fr)؟',
        'options': [
            '3 صفوف متساوية',
            '3 أعمدة متساوية العرض',
            '3 حدود فقط',
            'إلغاء الشبكة',
        ],
        'correct_answer': 1,
        'explanation': 'repeat(3, 1fr) ينشئ 3 أعمدة بعرض متساوٍ.',
        'topic': 'css',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي خاصية تتحكم بترتيب طبقات العناصر المتداخلة؟',
        'options': ['order-layer', 'z-index', 'stack', 'depth'],
        'correct_answer': 1,
        'explanation': 'z-index يحدد ترتيب العناصر على المحور Z.',
        'topic': 'css',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    # JavaScript - Beginner
    {
        'question': 'أي كلمة مفتاحية تعلن عن متغير لا يمكن إعادة تعيينه؟',
        'options': ['var', 'let', 'const', 'static'],
        'correct_answer': 2,
        'explanation': 'const يمنع إعادة تعيين المرجع للمتغير.',
        'topic': 'javascript',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'ما ناتج typeof "hello"؟',
        'options': ['string', 'text', 'char', 'object'],
        'correct_answer': 0,
        'explanation': 'typeof يعيد "string" للنصوص.',
        'topic': 'javascript',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'أي دالة تضيف عنصراً في نهاية المصفوفة؟',
        'options': ['push()', 'pop()', 'shift()', 'slice()'],
        'correct_answer': 0,
        'explanation': 'push() تضيف عنصراً في نهاية المصفوفة.',
        'topic': 'javascript',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    {
        'question': 'كيف تكتب تعليقاً في JavaScript؟',
        'options': ['<!-- comment -->', '// comment', '# comment', '/* comment'],
        'correct_answer': 1,
        'explanation': '// للتعليق السطري و /* */ للتعليق المتعدد الأسطر.',
        'topic': 'javascript',
        'difficulty_level': 'beginner',
        'difficulty_score': DIFFICULTY_SCORES['beginner'],
    },
    # JavaScript - Intermediate
    {
        'question': 'ما ناتج Boolean([])؟',
        'options': ['false', 'true', 'undefined', 'null'],
        'correct_answer': 1,
        'explanation': 'المصفوفة الفارغة قيمة truthy في JavaScript.',
        'topic': 'javascript',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'أي طريقة تنفّذ دالة لكل عنصر في المصفوفة؟',
        'options': ['map()', 'forEach()', 'reduce()', 'كل ما سبق'],
        'correct_answer': 3,
        'explanation': 'map وforEach وreduce كلها تمر على عناصر المصفوفة بطرق مختلفة.',
        'topic': 'javascript',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'ما الفرق بين == و ===؟',
        'options': [
            'لا فرق',
            '=== يقارن القيمة والنوع',
            '== يقارن النوع فقط',
            '=== أبطأ دائماً ولا يُستخدم',
        ],
        'correct_answer': 1,
        'explanation': '=== مقارنة صارمة بدون تحويل نوع ضمني.',
        'topic': 'javascript',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    {
        'question': 'كيف تصل إلى خاصية كائن بشكل آمن إن كان الكائن قد يكون null؟',
        'options': ['obj.prop!', 'obj?.prop', 'obj->prop', 'obj::prop'],
        'correct_answer': 1,
        'explanation': 'optional chaining ?. يمنع الخطأ عند null/undefined.',
        'topic': 'javascript',
        'difficulty_level': 'intermediate',
        'difficulty_score': DIFFICULTY_SCORES['intermediate'],
    },
    # JavaScript - Advanced
    {
        'question': 'ما ناتج [1, 2, 3].filter(n => n > 1)؟',
        'options': ['[1]', '[2, 3]', '[1,2,3]', 'true'],
        'correct_answer': 1,
        'explanation': 'filter يعيد عناصر تحقق الشرط فقط.',
        'topic': 'javascript',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي مفهوم يسمح بدالة تتذكر نطاقها الخارجي؟',
        'options': ['Prototype', 'Closure', 'Event loop', 'Hoisting only'],
        'correct_answer': 1,
        'explanation': 'Closure يحتفظ بالوصول لمتغيرات النطاق الخارجي.',
        'topic': 'javascript',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'ما ناتج JSON.parse(\'{"a":1}\')؟',
        'options': ['كائن JavaScript', 'نص JSON', 'undefined', 'رقم فقط'],
        'correct_answer': 0,
        'explanation': 'JSON.parse يحوّل نص JSON إلى كائن JavaScript.',
        'topic': 'javascript',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    {
        'question': 'أي وعد Promise يُنفّذ عند الفشل؟',
        'options': ['then', 'catch', 'finally only', 'await only'],
        'correct_answer': 1,
        'explanation': 'catch يعالج أخطاء الوعود المرفوضة.',
        'topic': 'javascript',
        'difficulty_level': 'advanced',
        'difficulty_score': DIFFICULTY_SCORES['advanced'],
    },
    # JavaScript - Expert
    {
        'question': 'ما دور event loop في JavaScript؟',
        'options': [
            'تنفيذ CSS',
            'إدارة المهام غير المتزامنة وطابور الاستدعاءات',
            'إنشاء عناصر DOM',
            'تشفير البيانات',
        ],
        'correct_answer': 1,
        'explanation': 'event loop ينسّق تنفيذ المهام غير المتزامنة.',
        'topic': 'javascript',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما الفرق بين let و var في النطاق scope؟',
        'options': [
            'let له نطاق كتلي و var له نطاق دالة',
            'var له نطاق كتلي فقط',
            'لا فرق',
            'let عام دائماً',
        ],
        'correct_answer': 0,
        'explanation': 'let/const block-scoped بينما var function-scoped.',
        'topic': 'javascript',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'أي طريقة تُنشئ نسخة سطحية من كائن؟',
        'options': ['Object.assign({}, obj)', 'obj.clone()', 'copy obj', 'obj.duplicate()'],
        'correct_answer': 0,
        'explanation': 'Object.assign أو spread {...obj} ينسخان سطحياً.',
        'topic': 'javascript',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
    {
        'question': 'ما ناتج async function foo() { return 1 } عند await foo()؟',
        'options': ['Promise فقط', '1', 'undefined دائماً', 'خطأ'],
        'correct_answer': 1,
        'explanation': 'await يستخرج القيمة المحلولة من الوعد.',
        'topic': 'javascript',
        'difficulty_level': 'expert',
        'difficulty_score': DIFFICULTY_SCORES['expert'],
    },
]
