# Generated by Django 6.0.4 on 2026-07-02 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('options', models.JSONField(verbose_name='الخيارات')),
                ('correct_answer', models.PositiveSmallIntegerField(help_text='فهرس الخيار الصحيح يبدأ من 0', verbose_name='رقم الإجابة الصحيحة')),
                ('explanation', models.TextField(verbose_name='الشرح')),
                ('topic', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JAVASCRIPT')], max_length=20, verbose_name='الموضوع')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, verbose_name='مستوى الصعوبة')),
                ('difficulty_score', models.FloatField(verbose_name='درجة الصعوبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال تحديد مستوى',
                'verbose_name_plural': 'بنك أسئلة تحديد المستوى',
                'ordering': ['topic', 'difficulty_score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='in_progress', max_length=20)),
                ('ability_score', models.FloatField(default=0.0)),
                ('final_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, null=True)),
                ('asked_question_ids', models.JSONField(blank=True, default=list)),
                ('responses', models.JSONField(blank=True, default=list)),
                ('total_questions', models.PositiveSmallIntegerField(default=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محاولة اختبار تحديد مستوى',
                'verbose_name_plural': 'محاولات اختبار تحديد المستوى',
                'ordering': ['-started_at'],
            },
        ),
    ]
