# Generated by Django 6.0 on 2026-07-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementattempt',
            name='random_seed',
            field=models.PositiveIntegerField(default=0, help_text='بذرة فريدة لكل محاولة لاختيار أسئلة مختلفة بين الطلاب', verbose_name='بذرة عشوائية'),
        ),
    ]
