# Generated by Django 6.0 on 2026-07-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placementattempt_random_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='source',
            field=models.CharField(
                choices=[('manual', 'يدوي'), ('ai', 'ذكاء اصطناعي')],
                default='manual',
                max_length=20,
                verbose_name='المصدر',
            ),
        ),
        migrations.AddField(
            model_name='placementquestion',
            name='attempt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='generated_questions',
                to='placement.placementattempt',
                verbose_name='المحاولة',
            ),
        ),
    ]
