# Generated by Django 6.0 on 2026-07-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementquestion_source_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='track_slug',
            field=models.CharField(
                choices=[('frontend', 'Frontend'), ('python', 'Python')],
                default='frontend',
                max_length=20,
                verbose_name='المسار',
            ),
        ),
    ]
