# Generated by Django 6.0 on 2026-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_rename_grade_percentage_projectprogress_grade_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='ai_suggestions',
            field=models.TextField(blank=True, null=True, verbose_name='اقتراحات الذكاء الاصطناعي'),
        ),
    ]
