# Generated by Django 6.0.4 on 2026-07-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_projectprogress_ai_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='ai_suggestions',
        ),
    ]
