# Generated by Django 6.0 on 2026-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='قم برفع صورة تعبيرية للمسار تظهر في البطاقات', null=True, upload_to='course_images/', verbose_name='صورة المسار'),
        ),
    ]
